// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         projectName: "claims_refund_v1",
 *         summary: "Refund $240 on claim C-1029",
 *         taskId: "taskId"
 *     }
 */
export interface CreateApprovalRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Upload ids of attached files to render for this request (must already be attached to the task) */
    attachments?: string[];
    /** Optional link to the agent author's observability trace */
    externalTraceId?: string;
    /** Display context as a plain key→value object (order/dup-keys are the client's concern) */
    keyValueContext?: Record<string, string>;
    /** Slug of an existing project (create it ahead of time) */
    projectName: string;
    recommendation?: PumpUp.ApprovalRecommendation;
    /** Human-readable summary of the action needing approval */
    summary: string;
    /** Target task — create one via POST /tasks first */
    taskId: string;
}
