// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         name: "Claim C-1029",
 *         projectName: "claims_refund_v1"
 *     }
 */
export interface CreateTaskRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Optional client correlation id (e.g. agent session/run); bookkeeping only — not unique */
    externalId?: string;
    metadataPatch?: PumpUp.MetadataPatchDto;
    /** Human-readable case name */
    name: string;
    /** Slug of an existing project */
    projectName: string;
}
