// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface TasksEventsRequest {
    id: string;
    cursor?: string;
    limit?: number;
}
