// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface TasksListRequest {
    projectId?: PumpUp.ObjectId;
    name?: string;
}
