// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface Action {
    addAttachments?: PumpUp.Attachment[] | undefined;
    description: string;
    detail?: Action.Detail | undefined;
    metadataPatch: PumpUp.MetadataPatch;
}

export namespace Action {
    export interface Detail {
        empty?: boolean | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
