// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ApprovalRequested {
    attachments?: string[] | undefined;
    keyValueContext?: Record<string, string> | undefined;
    recommendation?: PumpUp.ApprovalRecommendation | undefined;
    summary: string;
}
