// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ApprovalDecided {
    authority?: PumpUp.AuthoritySnapshot | undefined;
    outcome: PumpUp.Outcome;
    recommendationSnapshot?: PumpUp.ApprovalRecommendation | undefined;
}
