// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ApprovalResult {
    authoritySnapshot?: PumpUp.AuthoritySnapshot | undefined;
    decidedAt?: string | undefined;
    decidedBy?: string | undefined;
    outcome?: PumpUp.Outcome | undefined;
    recommendationSnapshot?: PumpUp.ApprovalRecommendation | undefined;
    requestId?: string | undefined;
    taskId?: string | undefined;
}
