// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface Attachment {
    label: string;
    uploadId?: PumpUp.ObjectId | undefined;
}
