// This file was auto-generated by Fern from our API Definition.

export interface DateTime {
    description?: string | undefined;
    id: string;
    label: string;
    max?: string | undefined;
    min?: string | undefined;
    required?: boolean | undefined;
}
