// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ElicitationRequested {
    attachments?: string[] | undefined;
    fields?: ElicitationRequested.Fields.Item[] | undefined;
    keyValueContext?: Record<string, string> | undefined;
    recommendation?: PumpUp.FieldBid[] | undefined;
    summary: string;
}

export namespace ElicitationRequested {
    export type Fields = Fields.Item[];

    export namespace Fields {
        export type Item =
            | PumpUp.DateField
            | PumpUp.DateTime
            | PumpUp.Multiselect
            | PumpUp.Number
            | PumpUp.Select
            | PumpUp.Slider
            | PumpUp.Switch
            | PumpUp.Text
            | PumpUp.TextArea
            | PumpUp.Time;
    }
}
