// This file was auto-generated by Fern from our API Definition.

export interface ElicitationResult {
    answeredAt?: string | undefined;
    answeredBy?: string | undefined;
    fields?: Record<string, unknown> | undefined;
    requestId?: string | undefined;
    taskId?: string | undefined;
}
