// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface EventRow {
    eventType: EventRow.EventType;
    externalTraceId?: string | undefined;
    id: string;
    inResponseTo?: string | undefined;
    owner: EventRow.Owner;
    payload: PumpUp.Payload;
    projectId: string;
    source: EventRow.Source;
    taskId: string;
    timestamp: string;
    transitionFrom?: string | undefined;
    transitionTo?: string | undefined;
}

export namespace EventRow {
    export const EventType = {
        ApprovalRequested: "APPROVAL_REQUESTED",
        ApprovalDecided: "APPROVAL_DECIDED",
        ElicitationRequested: "ELICITATION_REQUESTED",
        ElicitationProvided: "ELICITATION_PROVIDED",
        Action: "ACTION",
        Exception: "EXCEPTION",
        Note: "NOTE",
        Timeout: "TIMEOUT",
        Assignment: "ASSIGNMENT",
        TaskCreated: "TASK_CREATED",
        TaskClosed: "TASK_CLOSED",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
    export const Owner = {
        Agent: "AGENT",
        Human: "HUMAN",
        Platform: "PLATFORM",
    } as const;
    export type Owner = (typeof Owner)[keyof typeof Owner];
    export const Source = {
        Agent: "AGENT",
        Human: "HUMAN",
        Platform: "PLATFORM",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
}
