// This file was auto-generated by Fern from our API Definition.

export interface ExceptionRaised {
    detail?: ExceptionRaised.Detail | undefined;
    message: string;
}

export namespace ExceptionRaised {
    export interface Detail {
        empty?: boolean | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
