// This file was auto-generated by Fern from our API Definition.

export interface FieldBid {
    confidence?: number | undefined;
    fieldId?: string | undefined;
    rationale?: string | undefined;
    value?: unknown | undefined;
}
