// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export type Field =
    | PumpUp.Field.DateField
    | PumpUp.Field.DateTime
    | PumpUp.Field.Multiselect
    | PumpUp.Field.Number
    | PumpUp.Field.Select
    | PumpUp.Field.Slider
    | PumpUp.Field.Switch
    | PumpUp.Field.Text
    | PumpUp.Field.TextArea
    | PumpUp.Field.Time;

export namespace Field {
    export interface DateField extends PumpUp.DateField {
        type: "DateField";
    }

    export interface DateTime extends PumpUp.DateTime {
        type: "DateTime";
    }

    export interface Multiselect extends PumpUp.Multiselect {
        type: "Multiselect";
    }

    export interface Number extends PumpUp.Number {
        type: "Number";
    }

    export interface Select extends PumpUp.Select {
        type: "Select";
    }

    export interface Slider extends PumpUp.Slider {
        type: "Slider";
    }

    export interface Switch extends PumpUp.Switch {
        type: "Switch";
    }

    export interface Text extends PumpUp.Text {
        type: "Text";
    }

    export interface TextArea extends PumpUp.TextArea {
        type: "TextArea";
    }

    export interface Time extends PumpUp.Time {
        type: "Time";
    }
}
