// This file was auto-generated by Fern from our API Definition.

export interface MetadataPatchDto {
    set?: Record<string, unknown> | undefined;
    setOnce?: Record<string, unknown> | undefined;
    unset?: string[] | undefined;
}
