// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface MetadataPatch {
    empty?: boolean | undefined;
    set?: PumpUp.Document | undefined;
    setOnce?: PumpUp.Document | undefined;
    unset?: string[] | undefined;
}
