// This file was auto-generated by Fern from our API Definition.

export interface Number {
    description?: string | undefined;
    id: string;
    integerOnly: boolean;
    label: string;
    max?: number | undefined;
    min?: number | undefined;
    required: boolean;
}
