// This file was auto-generated by Fern from our API Definition.

export interface OpenRequestDto {
    eventType?: OpenRequestDto.EventType | undefined;
    requestId?: string | undefined;
    requestedAt?: string | undefined;
    summary?: string | undefined;
}

export namespace OpenRequestDto {
    export const EventType = {
        ApprovalRequested: "APPROVAL_REQUESTED",
        ApprovalDecided: "APPROVAL_DECIDED",
        ElicitationRequested: "ELICITATION_REQUESTED",
        ElicitationProvided: "ELICITATION_PROVIDED",
        Action: "ACTION",
        Exception: "EXCEPTION",
        Note: "NOTE",
        Timeout: "TIMEOUT",
        Assignment: "ASSIGNMENT",
        TaskCreated: "TASK_CREATED",
        TaskClosed: "TASK_CLOSED",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
}
