// This file was auto-generated by Fern from our API Definition.

export interface Outcome {
    note?: string | undefined;
    reasonCode?: string | undefined;
    type?: Outcome.Type | undefined;
}

export namespace Outcome {
    export const Type = {
        Approve: "APPROVE",
        Reject: "REJECT",
        EditAndApprove: "EDIT_AND_APPROVE",
        Escalate: "ESCALATE",
        RequestMoreInfo: "REQUEST_MORE_INFO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
