// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export type Payload =
    | PumpUp.Payload.Action
    | PumpUp.Payload.ApprovalDecided
    | PumpUp.Payload.ApprovalRequested
    | PumpUp.Payload.Assignment
    | PumpUp.Payload.ElicitationProvided
    | PumpUp.Payload.ElicitationRequested
    | PumpUp.Payload.ExceptionRaised
    | PumpUp.Payload.Note
    | PumpUp.Payload.TaskClosed
    | PumpUp.Payload.TaskCreated
    | PumpUp.Payload.Timeout;

export namespace Payload {
    export interface Action extends PumpUp.Action {
        type: "Action";
    }

    export interface ApprovalDecided extends PumpUp.ApprovalDecided {
        type: "ApprovalDecided";
    }

    export interface ApprovalRequested extends PumpUp.ApprovalRequested {
        type: "ApprovalRequested";
    }

    export interface Assignment extends PumpUp.Assignment {
        type: "Assignment";
    }

    export interface ElicitationProvided extends PumpUp.ElicitationProvided {
        type: "ElicitationProvided";
    }

    export interface ElicitationRequested extends PumpUp.ElicitationRequested {
        type: "ElicitationRequested";
    }

    export interface ExceptionRaised extends PumpUp.ExceptionRaised {
        type: "ExceptionRaised";
    }

    export interface Note extends PumpUp.Note {
        type: "Note";
    }

    export interface TaskClosed extends PumpUp.TaskClosed {
        type: "TaskClosed";
    }

    export interface TaskCreated extends PumpUp.TaskCreated {
        type: "TaskCreated";
    }

    export interface Timeout extends PumpUp.Timeout {
        type: "Timeout";
    }
}
