// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ProjectResponse {
    id?: string | undefined;
    /** Human-readable display name */
    name?: string | undefined;
    /** The slug — reference the project by this on ingest */
    projectName?: string | undefined;
    steps?: PumpUp.Steps | undefined;
}
