// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface ResolvedUpload {
    contentType?: string | undefined;
    id?: PumpUp.ObjectId | undefined;
    size?: number | undefined;
    url?: string | undefined;
}
