// This file was auto-generated by Fern from our API Definition.

export interface Select {
    description?: string | undefined;
    id: string;
    label: string;
    options?: string[] | undefined;
    required?: boolean | undefined;
}
