// This file was auto-generated by Fern from our API Definition.

export interface Slider {
    description?: string | undefined;
    id: string;
    label: string;
    max?: number | undefined;
    min?: number | undefined;
    required?: boolean | undefined;
    step?: number | undefined;
}
