// This file was auto-generated by Fern from our API Definition.

export interface Slider {
    description?: string | undefined;
    id: string;
    label: string;
    max: number;
    min: number;
    required: boolean;
    step?: number | undefined;
}
