// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface Steps {
    initialState: string;
    stateSchemas?: Steps.StateSchemas | undefined;
    steps: PumpUp.Step[];
}

export namespace Steps {
    export interface StateSchemas {
        empty?: boolean | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
