// This file was auto-generated by Fern from our API Definition.

export interface Step {
    exits?: string[] | undefined;
    name?: string | undefined;
    owner?: Step.Owner | undefined;
}

export namespace Step {
    export const Owner = {
        Agent: "AGENT",
        Human: "HUMAN",
        Platform: "PLATFORM",
    } as const;
    export type Owner = (typeof Owner)[keyof typeof Owner];
}
