// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface Steps {
    initialStep: string;
    stepSchemas?: PumpUp.Document | undefined;
    steps: PumpUp.Step[];
}
