// This file was auto-generated by Fern from our API Definition.

export interface Switch {
    description?: string | undefined;
    id: string;
    label: string;
    required?: boolean | undefined;
}
