// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface TaskDetailResponse {
    openRequests?: PumpUp.OpenRequestDto[] | undefined;
    task?: PumpUp.TaskResponse | undefined;
}
