// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface TaskResponse {
    attachments?: PumpUp.Attachment[] | undefined;
    currentStep: string;
    externalId?: string | undefined;
    id: string;
    metadata?: Record<string, unknown> | undefined;
    name: string;
    projectId: string;
    status: TaskResponse.Status;
}

export namespace TaskResponse {
    export const Status = {
        Running: "RUNNING",
        Waiting: "WAITING",
        Closed: "CLOSED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
