// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface TaskResponse {
    attachments?: PumpUp.Attachment[] | undefined;
    currentState?: string | undefined;
    id?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    name?: string | undefined;
    projectId?: string | undefined;
    status?: TaskResponse.Status | undefined;
}

export namespace TaskResponse {
    export const Status = {
        Open: "OPEN",
        Closed: "CLOSED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
