// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface TaskCreated {
    initialState: string;
    metadataPatch: PumpUp.MetadataPatch;
    name: string;
}
