// This file was auto-generated by Fern from our API Definition.

export interface TextArea {
    description?: string | undefined;
    id: string;
    label: string;
    maxLength?: number | undefined;
    minLength?: number | undefined;
    required?: boolean | undefined;
}
