// This file was auto-generated by Fern from our API Definition.

export interface Text {
    description?: string | undefined;
    format?: Text.Format | undefined;
    id: string;
    label: string;
    maxLength?: number | undefined;
    minLength?: number | undefined;
    required?: boolean | undefined;
}

export namespace Text {
    export const Format = {
        Email: "EMAIL",
        Phone: "PHONE",
        Url: "URL",
    } as const;
    export type Format = (typeof Format)[keyof typeof Format];
}
