// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../index.js";

export interface UploadRef {
    id?: PumpUp.ObjectId | undefined;
    status?: UploadRef.Status | undefined;
}

export namespace UploadRef {
    export const Status = {
        Ready: "READY",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
