// This file was auto-generated by Fern from our API Definition.

export interface UploadRef {
    id: string;
    status: UploadRef.Status;
}

export namespace UploadRef {
    export const Status = {
        Ready: "READY",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
