// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         description: "Auto-classified claim as low-risk",
 *         projectName: "projectName"
 *     }
 */
export interface AgentActionRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Files to attach to the task — upload id + display name (each id from POST /uploads) */
    addAttachments?: PumpUp.Attachment[];
    /** What the agent did */
    description: string;
    detail?: Record<string, unknown>;
    externalTraceId?: string;
    metadataPatch?: PumpUp.MetadataPatchDto;
    projectName: string;
    taskId?: string;
    /** State to transition the task into; must be a declared transition */
    transitionsTo?: string;
}
