// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         message: "OCR failed on uploaded document",
 *         projectName: "projectName"
 *     }
 */
export interface ExceptionRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Files to attach to the task — upload id + display name (each id from POST /uploads) */
    addAttachments?: PumpUp.Attachment[];
    detail?: Record<string, unknown>;
    externalTraceId?: string;
    /** What went wrong */
    message: string;
    metadataPatch?: PumpUp.MetadataPatchDto;
    projectName: string;
    taskId?: string;
    transitionsTo?: string;
}
