// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         message: "OCR failed on uploaded document",
 *         projectName: "projectName",
 *         taskId: "taskId"
 *     }
 */
export interface ExceptionRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    detail?: Record<string, unknown>;
    externalTraceId?: string;
    /** What went wrong */
    message: string;
    projectName: string;
    /** Target task — create one via POST /tasks first */
    taskId: string;
    transitionsTo?: string;
}
