// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         message: "Customer called to confirm bank details",
 *         projectName: "projectName"
 *     }
 */
export interface NoteRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    externalTraceId?: string;
    /** The annotation text */
    message: string;
    projectName: string;
    taskId?: string;
}
