// This file was auto-generated by Fern from our API Definition.

import * as PumpUp from "../../src/api/index";
import { PumpUpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ElicitationsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            fields: [{ id: "id", label: "label" }],
            projectName: "projectName",
            summary: "Need additional details on the incident",
        };
        const rawResponseBody = { eventId: "665f1a2b3c4d5e6f7a8b9c0d" };

        server
            .mockEndpoint()
            .post("/api/elicitation-requests")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.elicitations.create({
            "Idempotency-Key": "Idempotency-Key",
            fields: [
                {
                    id: "id",
                    label: "label",
                },
            ],
            projectName: "projectName",
            summary: "Need additional details on the incident",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            fields: [
                { id: "x", label: "x" },
                { id: "x", label: "x" },
            ],
            projectName: "x",
            summary: "x",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/elicitation-requests")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.create({
                "Idempotency-Key": "idempotencyKey",
                fields: [
                    {
                        id: "x",
                        label: "x",
                    },
                    {
                        id: "x",
                        label: "x",
                    },
                ],
                projectName: "x",
                summary: "x",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            fields: [
                { id: "x", label: "x" },
                { id: "x", label: "x" },
            ],
            projectName: "x",
            summary: "x",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/elicitation-requests")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.create({
                "Idempotency-Key": "idempotencyKey",
                fields: [
                    {
                        id: "x",
                        label: "x",
                    },
                    {
                        id: "x",
                        label: "x",
                    },
                ],
                projectName: "x",
                summary: "x",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            fields: [
                { id: "x", label: "x" },
                { id: "x", label: "x" },
            ],
            projectName: "x",
            summary: "x",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/elicitation-requests")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.create({
                "Idempotency-Key": "idempotencyKey",
                fields: [
                    {
                        id: "x",
                        label: "x",
                    },
                    {
                        id: "x",
                        label: "x",
                    },
                ],
                projectName: "x",
                summary: "x",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            fields: [
                { id: "x", label: "x" },
                { id: "x", label: "x" },
            ],
            projectName: "x",
            summary: "x",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/elicitation-requests")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.create({
                "Idempotency-Key": "idempotencyKey",
                fields: [
                    {
                        id: "x",
                        label: "x",
                    },
                    {
                        id: "x",
                        label: "x",
                    },
                ],
                projectName: "x",
                summary: "x",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("getResult (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            answeredAt: "2024-01-15T09:30:00Z",
            answeredBy: "answeredBy",
            fields: { fields: { key: "value" } },
            requestId: "requestId",
            taskId: "taskId",
        };

        server
            .mockEndpoint()
            .get("/api/elicitation-requests/id/result")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.elicitations.getResult({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getResult (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/elicitation-requests/id/result")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.getResult({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("getResult (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/elicitation-requests/id/result")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.getResult({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("getResult (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/elicitation-requests/id/result")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.getResult({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("getResult (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/elicitation-requests/id/result")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.elicitations.getResult({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });
});
