// This file was auto-generated by Fern from our API Definition.

import * as PumpUp from "../../src/api/index";
import { PumpUpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventsClient", () => {
    test("agentAction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { description: "Auto-classified claim as low-risk", projectName: "projectName" };
        const rawResponseBody = { eventId: "665f1a2b3c4d5e6f7a8b9c0d" };

        server
            .mockEndpoint()
            .post("/api/agent-actions")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.agentAction({
            "Idempotency-Key": "Idempotency-Key",
            description: "Auto-classified claim as low-risk",
            projectName: "projectName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("agentAction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { description: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/agent-actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.agentAction({
                "Idempotency-Key": "idempotencyKey",
                description: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("agentAction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { description: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/agent-actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.agentAction({
                "Idempotency-Key": "idempotencyKey",
                description: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("agentAction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { description: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/agent-actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.agentAction({
                "Idempotency-Key": "idempotencyKey",
                description: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("agentAction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { description: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/agent-actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.agentAction({
                "Idempotency-Key": "idempotencyKey",
                description: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("exception (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "OCR failed on uploaded document", projectName: "projectName" };
        const rawResponseBody = { eventId: "665f1a2b3c4d5e6f7a8b9c0d" };

        server
            .mockEndpoint()
            .post("/api/exceptions")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.exception({
            "Idempotency-Key": "Idempotency-Key",
            message: "OCR failed on uploaded document",
            projectName: "projectName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exception (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/exceptions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.exception({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("exception (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/exceptions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.exception({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("exception (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/exceptions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.exception({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("exception (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/exceptions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.exception({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("note (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "Customer called to confirm bank details", projectName: "projectName" };
        const rawResponseBody = { eventId: "665f1a2b3c4d5e6f7a8b9c0d" };

        server
            .mockEndpoint()
            .post("/api/notes")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.note({
            "Idempotency-Key": "Idempotency-Key",
            message: "Customer called to confirm bank details",
            projectName: "projectName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("note (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/notes")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.note({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("note (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/notes")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.note({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("note (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/notes")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.note({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("note (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { message: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/notes")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.note({
                "Idempotency-Key": "idempotencyKey",
                message: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });
});
