// This file was auto-generated by Fern from our API Definition.

import * as PumpUp from "../../src/api/index";
import { PumpUpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    name: "Claims Refund v1",
                    projectName: "claims_refund_v1",
                    steps: { initialState: "initialState", steps: [{}] },
                },
            ],
        };

        server.mockEndpoint().get("/api/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.list();
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.list();
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.list();
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.list();
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "id",
            name: "name",
            projectName: "projectName",
            steps: {
                initialState: "initialState",
                stateSchemas: { empty: true },
                steps: [
                    { exits: ["exits", "exits"], name: "name", owner: "AGENT" },
                    { exits: ["exits", "exits"], name: "name", owner: "AGENT" },
                ],
            },
        };

        server.mockEndpoint().get("/api/projects/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.get({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects/id").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/projects/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });
});
