// This file was auto-generated by Fern from our API Definition.

import * as PumpUp from "../../src/api/index";
import { PumpUpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TasksClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            items: [
                {
                    attachments: [{ label: "label" }],
                    currentState: "currentState",
                    id: "id",
                    metadata: { key: "value" },
                    name: "name",
                    projectId: "projectId",
                    status: "OPEN",
                },
            ],
        };

        server.mockEndpoint().get("/api/tasks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tasks.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.list();
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.list();
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.list();
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.list();
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Claim C-1029", projectName: "claims_refund_v1" };
        const rawResponseBody = {
            attachments: [{ label: "label" }],
            currentState: "currentState",
            id: "id",
            metadata: { key: "value" },
            name: "name",
            projectId: "projectId",
            status: "OPEN",
        };

        server
            .mockEndpoint()
            .post("/api/tasks")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tasks.create({
            "Idempotency-Key": "Idempotency-Key",
            name: "Claim C-1029",
            projectName: "claims_refund_v1",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/tasks")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tasks.create({
                "Idempotency-Key": "idempotencyKey",
                name: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/tasks")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tasks.create({
                "Idempotency-Key": "idempotencyKey",
                name: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/tasks")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tasks.create({
                "Idempotency-Key": "idempotencyKey",
                name: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", projectName: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/tasks")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tasks.create({
                "Idempotency-Key": "idempotencyKey",
                name: "x",
                projectName: "x",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            openRequests: [
                {
                    eventType: "APPROVAL_REQUESTED",
                    requestId: "requestId",
                    requestedAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                },
                {
                    eventType: "APPROVAL_REQUESTED",
                    requestId: "requestId",
                    requestedAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                },
            ],
            task: {
                attachments: [
                    { label: "x", uploadId: { date: "2024-01-15T09:30:00Z", timestamp: 1 } },
                    { label: "x", uploadId: { date: "2024-01-15T09:30:00Z", timestamp: 1 } },
                ],
                currentState: "currentState",
                id: "id",
                metadata: { metadata: { key: "value" } },
                name: "name",
                projectId: "projectId",
                status: "OPEN",
            },
        };

        server.mockEndpoint().get("/api/tasks/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tasks.get({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks/id").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/tasks/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tasks.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });
});
