// This file was auto-generated by Fern from our API Definition.

import * as PumpUp from "../../src/api/index";
import { PumpUpClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UploadsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            contentType: "contentType",
            id: { date: "2024-01-15T09:30:00Z", timestamp: 1 },
            size: 1000000,
            url: "url",
        };

        server.mockEndpoint().get("/api/uploads/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.uploads.get({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/uploads/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.uploads.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/uploads/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.uploads.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/uploads/id").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.uploads.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.ConflictError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PumpUpClient({
            maxRetries: 0,
            apiKey: "test",
            version: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/uploads/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.uploads.get({
                id: "id",
            });
        }).rejects.toThrow(PumpUp.InternalServerError);
    });
});
