// This file was auto-generated by Fern from our API Definition.

import { ApprovalsClient } from "./api/resources/approvals/client/Client.js";
import { ElicitationsClient } from "./api/resources/elicitations/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import { UploadsClient } from "./api/resources/uploads/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace PumpUpClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PumpUpClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PumpUpClient.Options>;
    protected _events: EventsClient | undefined;
    protected _approvals: ApprovalsClient | undefined;
    protected _elicitations: ElicitationsClient | undefined;
    protected _projects: ProjectsClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _uploads: UploadsClient | undefined;

    constructor(options: PumpUpClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get approvals(): ApprovalsClient {
        return (this._approvals ??= new ApprovalsClient(this._options));
    }

    public get elicitations(): ElicitationsClient {
        return (this._elicitations ??= new ElicitationsClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get uploads(): UploadsClient {
        return (this._uploads ??= new UploadsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
