// This file was auto-generated by Fern from our API Definition.

export const PumpUpEnvironment = {
    Default: "https://api.pumpup.com",
} as const;

export type PumpUpEnvironment = typeof PumpUpEnvironment.Default;
