// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         fields: [{
 *                 type: "DateField",
 *                 id: "id",
 *                 label: "label",
 *                 required: true
 *             }],
 *         projectName: "projectName",
 *         summary: "Need additional details on the incident",
 *         taskId: "taskId"
 *     }
 */
export interface CreateElicitationRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Upload ids of attached files to render for this request (must already be attached to the task) */
    attachments?: string[];
    externalTraceId?: string;
    fields: PumpUp.Field[];
    keyValueContext?: Record<string, string>;
    projectName: string;
    recommendation?: PumpUp.FieldBid[];
    /** Human-readable summary of what's needed */
    summary: string;
    /** Target task — create one via POST /tasks first */
    taskId: string;
}
