// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         fields: [{
 *                 id: "id",
 *                 label: "label"
 *             }],
 *         projectName: "projectName",
 *         summary: "Need additional details on the incident"
 *     }
 */
export interface CreateElicitationRequest {
    /** Idempotency key; duplicate submissions return the original event. */
    "Idempotency-Key": string;
    /** Files to attach to the task — upload id + display name (each id from POST /uploads) */
    addAttachments?: PumpUp.Attachment[];
    /** Upload ids of attached files to render for this request (must already be attached to the task) */
    attachments?: PumpUp.ObjectId[];
    externalTraceId?: string;
    fields: CreateElicitationRequest.Fields.Item[];
    keyValueContext?: Record<string, string>;
    metadataPatch?: PumpUp.MetadataPatchDto;
    projectName: string;
    recommendation?: PumpUp.FieldBid[];
    /** Human-readable summary of what's needed */
    summary: string;
    taskId?: string;
}

export namespace CreateElicitationRequest {
    export type Fields = Fields.Item[];

    export namespace Fields {
        export type Item =
            | PumpUp.DateField
            | PumpUp.DateTime
            | PumpUp.Multiselect
            | PumpUp.Number
            | PumpUp.Select
            | PumpUp.Slider
            | PumpUp.Switch
            | PumpUp.Text
            | PumpUp.TextArea
            | PumpUp.Time;
    }
}
