// This file was auto-generated by Fern from our API Definition.

import type * as PumpUp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ElicitationsGetResultRequest {
    id: PumpUp.ObjectId;
}
